### ISSUE TITLE
Map not updating when a signature is deleted from the list

### ISSUE THREAD

**Issue by MiSwit13** [w9jds/Galaxytracker#21]
I deleted a signature to our old C4 static but the chain remained on the map even though the sig id on the map node did change to [???]
![mapnotupdating](https://cloud.githubusercontent.com/assets/15026683/22994251/1d291f02-f37b-11e6-9b49-539f421b3901.JPG)

**Comment by w9jds** [comment]
This seems to be isolated to deleting from the signature table. Right clicking on the system in the map seems to delete properly.
