### ISSUE TITLE
Populate previous system sig info in new system

### ISSUE THREAD

**Issue by MiSwit13** [w9jds/Galaxytracker#22]
When I jump into a new system, I would like to have a signature pre-populated in the list with known information:

1. Signature ID: blank
2. Group: Wormhole
3. Wormhole Type: K162 (unless the signature in the previous system was of type K162, in which case the type would be blank)
4, System Name: Name of the previous system in the chain.

![populatedsig](https://cloud.githubusercontent.com/assets/15026683/22994956/a8cf7518-f37d-11e6-9a08-c92145c0d7c8.JPG)

**Comment by w9jds** [comment]
I created a home button instead, so instead of having to edit this one with the proper signature id and deleting something you paste you just click the home button instead which auto populates the parent system data instead.
